Dmitry/hero adaptive
Maestr1/lubimovka_9th_team pull request #16
Opened 2022-10-22 16:50 UTC by Maestr1

Проверьте плиз

2022-10-25 10:25 UTC, ground-aero requested changes
Дмитрий, посмотри пожалуйста, по мобильному макету, буквально пару совсем небольших предложений

2022-10-25 10:25 UTC, ground-aero commented on blocks/hero/__pic/hero__pic.css
> +    height: 415px;
похоже что зд. опечатка по параметру "высота" картинки.
согласно Фигме на мобильном макете  height: 450px;

2022-10-25 10:25 UTC, ground-aero commented on blocks/hero/__pic/hero__pic.css
> +
для точности отображения также можно вставить сюда картинку для мобильной версии background-image: url('../../../images/header-pic-mobile.png') - она как раз размером 414 х 450px

2022-11-07 14:49 UTC, Maestr1 commented
> Дмитрий, посмотри пожалуйста, по мобильному макету, буквально пару совсем небольших предложений

исправил, картинку отцентровал, лучше не использовать обрезанные версии для меньшего размера, тянуться будет не красиво

2022-11-07 14:49 UTC, merged